#!/bin/bash
# Creates /usr/bin/ and /etc/init.d/ symlinks, and runs update-rc.d

for f in $PWD/*/bin/*; do
  ln -fs "$f" "/usr/bin/$(basename $f)"
done

for f in $PWD/init_scripts/*; do
  name="$(basename $f)"
  ln -fs "$f" "/etc/init.d/$name"
  sudo update-rc.d "$name" defaults
done
