#! /bin/sh
# /etc/init.d/mw_access_point

### BEGIN INIT INFO
# Provides:          mw_access_point
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Setup Microwave Access Point
# Description:       Setup Microwave Access Point if no Wifi connection
### END INIT INFO

# Check wifi after a delay. If not connected, set up access point so we can configure wifi password
sleep 20
/home/ndbroadbent/raspberry_picrowave/access_point_if_no_wifi

exit 0